Repository Winds-Studio/Leaf, pull requests merged in 2025-03, with the labels that each got.

#235 Connection.flushQueue optimization
  leaf-server/minecraft-patches/features/0125-Rewrite-queue-on-Connection.flushQueue.patch
  leaf-server/minecraft-patches/features/0126-ShreddedPaper-Don-t-block-main-thread-in-Connection-.patch
  leaf-server/src/main/java/org/dreeam/leaf/config/modules/network/ConnectionFlushQueueRewrite.java
Labels: type: optimization

#231 Chunk improvements
  leaf-server/minecraft-patches/features/0127-ensureCapacity-with-collectTickingChunks.patch
  leaf-server/minecraft-patches/features/0128-Bulk-writes-to-writeLongArray-during-chunk-loading.patch
  leaf-server/minecraft-patches/features/0129-Use-BFS-on-getSlopeDistance-in-fluids.patch
  leaf-server/minecraft-patches/features/0130-Optimize-AABB.patch
  leaf-server/minecraft-patches/features/0131-Improve-sorting-in-SortedArraySet.patch
  leaf-server/minecraft-patches/features/0132-Make-removeIf-slightly-faster.patch
  leaf-server/minecraft-patches/features/0133-Optimize-LinearPalette.patch
  leaf-server/minecraft-patches/features/0134-Optimize-IdMapper.patch
  leaf-server/minecraft-patches/features/0135-Slight-optimizations-to-VarInt.patch
  leaf-server/minecraft-patches/features/0136-Rewrite-ClientboundLightUpdatePacketData.patch
  leaf-server/minecraft-patches/features/0137-Some-Optimizations-on-SerializableChunkData.patch
  leaf-server/minecraft-patches/features/0138-Rework-ChunkHolderManager.patch
  leaf-server/minecraft-patches/features/0139-Optimize-chunkUnload.patch
  leaf-server/minecraft-patches/features/0140-Async-ChunkSend.patch
  leaf-server/src/main/java/org/dreeam/leaf/config/modules/async/AsyncChunkSend.java
  leaf-server/src/main/java/org/dreeam/leaf/util/map/ConcurrentLongHashSet.java
Labels: type: optimization

#244 Update Workflow
  .github/workflows/build-1214.yml
  build.gradle.kts
  scripts/prepareRelease.sh
Labels: type: misc

#248 Fix Faster Random Generator
  leaf-server/minecraft-patches/features/0051-Faster-random-generator.patch
Labels: type: fix

#252 fix async chunk send
  leaf-server/minecraft-patches/features/0139-Async-ChunkSend.patch
Labels: type: fix

#251 Spawner Block settings
  leaf-server/minecraft-patches/features/0140-Spawner-Configurations.patch
  leaf-server/src/main/java/org/dreeam/leaf/config/modules/gameplay/SpawnerSettings.java
Labels: type: feature

#246 SparklyPaper: Parallel world ticking
  leaf-server/minecraft-patches/features/0141-SparklyPaper-Parallel-world-ticking.patch
  leaf-server/minecraft-patches/features/0142-Track-each-world-MSPT.patch
  leaf-server/paper-patches/features/0031-SparklyPaper-Parallel-world-ticking.patch
  leaf-server/src/main/java/org/dreeam/leaf/async/world/SparklyPaperServerLevelTickExecutorThreadFactory.java
  leaf-server/src/main/java/org/dreeam/leaf/command/LeafCommand.java
  leaf-server/src/main/java/org/dreeam/leaf/command/subcommands/MSPTCommand.java
  leaf-server/src/main/java/org/dreeam/leaf/config/modules/async/AsyncChunkSend.java
  leaf-server/src/main/java/org/dreeam/leaf/config/modules/async/SparklyPaperParallelWorldTicking.java
Labels: type: optimization

#262 Fix critical bugs with SparklyPaper parallel world ticking - part 2
  leaf-server/minecraft-patches/features/0141-SparklyPaper-Parallel-world-ticking.patch
  leaf-server/paper-patches/features/0031-SparklyPaper-Parallel-world-ticking.patch
Labels: type: fix

#269 Update async playerdata saving
  leaf-server/minecraft-patches/features/0086-Nitori-Async-playerdata-Save.patch
  leaf-server/paper-patches/features/0033-Async-playerdata-saving.patch
  leaf-server/src/main/java/org/dreeam/leaf/async/AsyncPlayerDataSaving.java
Labels: type: optimization
