Repository Winds-Studio/Leaf, pull requests merged in 2025-02, with the labels that each got.

#215 [Reimplement] Hide specified item components [for 1.21.4]
  leaf-server/minecraft-patches/features/0078-Hide-specified-item-components.patch
  leaf-server/minecraft-patches/features/0079-Paper-PR-Skip-AI-during-inactive-ticks-for-non-aware.patch
  leaf-server/minecraft-patches/features/0080-Paper-PR-Prevent-zombie-reinforcements-loading-chunk.patch
  leaf-server/minecraft-patches/features/0081-PaperPR-Fix-some-beacon-event-issues.patch
  leaf-server/minecraft-patches/features/0082-Dont-send-useless-entity-packets.patch
  leaf-server/minecraft-patches/features/0083-Don-t-spawn-if-lastSpawnState-is-null.patch
  leaf-server/minecraft-patches/features/0084-Multithreaded-Tracker.patch
  leaf-server/minecraft-patches/features/0085-Nitori-Async-playerdata-Save.patch
  leaf-server/minecraft-patches/features/0086-Optimize-nearby-alive-players-for-spawning.patch
  leaf-server/minecraft-patches/features/0087-Cache-blockstate-cache-array.patch
  leaf-server/minecraft-patches/features/0088-Asynchronous-locator.patch
  leaf-server/minecraft-patches/features/0089-Smart-sort-entities-in-NearestLivingEntitySensor.patch
  leaf-server/minecraft-patches/features/0090-Further-reduce-memory-footprint-of-CompoundTag.patch
  leaf-server/minecraft-patches/features/0091-Optimize-Entity-distanceToSqr.patch
  leaf-server/minecraft-patches/features/0092-EMC-Don-t-use-snapshots-for-TileEntity-getOwner.patch
  leaf-server/minecraft-patches/features/0093-Cache-tile-entity-position.patch
  leaf-server/minecraft-patches/features/0094-TT20-Lag-compensation.patch
  leaf-server/minecraft-patches/features/0095-C2ME-Reduce-Allocations.patch
  leaf-server/minecraft-patches/features/0096-Lithium-Skip-unnecessary-calculations-if-player-is-n.patch
  leaf-server/minecraft-patches/features/0097-Lithium-fast-util.patch
  leaf-server/minecraft-patches/features/0098-Lithium-CompactSineLUT.patch
  leaf-server/minecraft-patches/features/0099-Lithium-cached-iterate-outwards.patch
  leaf-server/minecraft-patches/features/0100-Smooth-teleport-config.patch
  leaf-server/minecraft-patches/features/0101-Use-faster-and-thread-safe-ban-list-date-format-pars.patch
  leaf-server/minecraft-patches/features/0102-Collect-then-startEachNonRunningBehavior-in-Brain.patch
  leaf-server/minecraft-patches/features/0103-Lithium-equipment-tracking.patch
  leaf-server/minecraft-patches/features/0104-C2ME-Optimize-world-gen-math.patch
  leaf-server/minecraft-patches/features/0105-Cache-chunk-key.patch
  leaf-server/minecraft-patches/features/0106-Cache-random-tick-block-status.patch
  leaf-server/minecraft-patches/features/0107-Cache-part-of-canHoldFluid-result.patch
  leaf-server/minecraft-patches/features/0108-Configurable-tripwire-dupe.patch
  leaf-server/src/main/java/org/dreeam/leaf/config/modules/gameplay/HideItemComponent.java
  leaf-server/src/main/java/org/dreeam/leaf/util/item/ItemStackStripper.java
Labels: type: fix

#210 Reimplement Hide specified item components
  patches/server/0103-Hide-specified-item-components-to-clients.patch
  patches/server/0103-Hide-specified-item-components.patch
  patches/server/0104-Paper-PR-Skip-AI-during-inactive-ticks-for-non-aware.patch
  patches/server/0107-Dont-send-useless-entity-packets.patch
  patches/server/0109-Multithreaded-Tracker.patch
  patches/server/0123-Lithium-Skip-unnecessary-calculations-if-player-is-n.patch
  patches/server/0131-Lithium-equipment-tracking.patch
Labels: type: fix

#218 Dont reallocate buckets again
  leaf-server/minecraft-patches/features/0089-Smart-sort-entities-in-NearestLivingEntitySensor.patch
Labels: type: optimization

#220 Async structure locate API
  leaf-api/paper-patches/features/0010-Async-structure-locate-api.patch
  leaf-server/paper-patches/features/0028-Async-structure-locate-api.patch
Labels: type: feature

#224 Thread safety fixes
  leaf-server/minecraft-patches/features/0084-Multithreaded-Tracker.patch
  leaf-server/paper-patches/features/0003-Pufferfish-Optimize-mob-spawning.patch
  leaf-server/src/main/java/org/dreeam/leaf/util/map/ConcurrentLongHashSet.java
Labels: type: fix

#226 Adjust default config values
  leaf-server/src/main/java/org/dreeam/leaf/config/modules/async/AsyncPathfinding.java
  leaf-server/src/main/java/org/dreeam/leaf/config/modules/async/MultithreadedTracker.java
Labels: type: fix, type: general

#227 Fix DAB entity blacklist
  leaf-server/src/main/java/org/dreeam/leaf/config/ConfigModules.java
  leaf-server/src/main/java/org/dreeam/leaf/config/modules/gameplay/SmoothTeleport.java
  leaf-server/src/main/java/org/dreeam/leaf/config/modules/opt/DynamicActivationofBrain.java
Labels: type: fix

#229 [ci skip]Impove template
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/en_bug_report.yml
  .github/ISSUE_TEMPLATE/zh_bug_report.yml
Labels: type: misc

#230 [ci skip] Impove template
  .github/ISSUE_TEMPLATE/en_bug_report.yml
  .github/ISSUE_TEMPLATE/en_feature_request.yml
Labels: type: misc

#232 Add PlayerInventoryOverflowEvent
  leaf-api/paper-patches/features/0011-PlayerInventoryOverflowEvent.patch
  leaf-server/paper-patches/features/0029-PlayerInventoryOverflowEvent.patch
Labels: type: feature

#217 Bunch of side perf improvements
  build-data/leaf.at
  leaf-archived-patches/removed/hardfork/server/0120-Replace-criterion-listener-map-with-optimized-collec.patch
  leaf-archived-patches/work/server/0110-Cache-ItemStack-max-stack-size.patch
  leaf-server/minecraft-patches/features/0089-Smart-sort-entities-in-NearestLivingEntitySensor.patch
  leaf-server/minecraft-patches/features/0109-PaperPR-Fix-MC-117075-Block-Entities-Unload-Lag-Spik.patch
  leaf-server/minecraft-patches/features/0110-Sepals-Rearrange-the-attackable-conditions.patch
  leaf-server/minecraft-patches/features/0111-SparklyPaper-Skip-dirty-stats-copy-when-requesting-p.patch
  leaf-server/minecraft-patches/features/0112-SparklyPaper-Reset-dirty-flag-when-loading-maps-from.patch
  leaf-server/minecraft-patches/features/0113-Optimize-checking-nearby-players-for-spawning.patch
  leaf-server/minecraft-patches/features/0114-Cache-supporting-block-check.patch
  leaf-server/minecraft-patches/features/0115-Avoid-useless-deque-clear-on-LevelTicks-cleanupAfter.patch
  leaf-server/minecraft-patches/features/0116-Replace-brain-activity-maps-with-optimized-collectio.patch
  leaf-server/minecraft-patches/features/0117-Remove-stream-in-villagers.patch
  leaf-server/minecraft-patches/features/0118-Optimize-baby-villager-sensor.patch
  leaf-server/minecraft-patches/features/0119-Only-player-pushable.patch
  leaf-server/minecraft-patches/features/0120-Remove-iterators-from-Inventory-contains.patch
  leaf-server/minecraft-patches/features/0121-Alternative-Brain-Behaviour.patch
  leaf-server/minecraft-patches/features/0122-Cache-eligible-players-for-despawn-checks.patch
  leaf-server/minecraft-patches/features/0123-Slightly-optimise-getNearestPlayer.patch
  leaf-server/src/main/java/org/dreeam/leaf/config/modules/gameplay/OnlyPlayerPushable.java
  leaf-server/src/main/java/org/dreeam/leaf/config/modules/opt/BrainRunningBehaviorCacheUpdate.java
  leaf-server/src/main/java/org/dreeam/leaf/util/list/BlockEntityTickersList.java
Labels: type: optimization

#236 Fix Multithreaded Tracker
  leaf-server/minecraft-patches/features/0085-Multithreaded-Tracker.patch
  leaf-server/src/main/java/org/dreeam/leaf/util/map/StringCanonizingOpenHashMap.java
Labels: type: fix

#241 Fix async entity tracker
  leaf-server/paper-patches/features/0024-Multithreaded-Tracker.patch
  leaf-server/src/main/java/org/dreeam/leaf/util/map/StringCanonizingOpenHashMap.java
Labels: type: fix
