Repository Winds-Studio/Leaf, pull requests merged in 2025-05, with the labels that each got.

#301 fix async chunk sending buffer
  leaf-server/minecraft-patches/features/0132-Async-chunk-sending.patch
  leaf-server/minecraft-patches/features/0157-Optimise-chunkUnloads.patch
  leaf-server/paper-patches/features/0034-Async-chunk-sending.patch
Labels: type: fix

#303 optimize async target finding
  leaf-server/minecraft-patches/features/0154-Async-target-finding.patch
  leaf-server/src/main/java/org/dreeam/leaf/async/ai/AsyncGoalExecutor.java
  leaf-server/src/main/java/org/dreeam/leaf/async/ai/AsyncGoalThread.java
  leaf-server/src/main/java/org/dreeam/leaf/async/ai/Waker.java
  leaf-server/src/main/java/org/dreeam/leaf/config/modules/async/AsyncTargetFinding.java
  leaf-server/src/main/java/org/dreeam/leaf/util/queue/SpscIntQueue.java
Labels: type: fix, type: optimization

#304 Update PlayerInventoryOverflowEvent
  leaf-api/paper-patches/features/0011-PlayerInventoryOverflowEvent.patch
  leaf-server/paper-patches/features/0030-PlayerInventoryOverflowEvent.patch
  leaf-server/src/main/java/org/dreeam/leaf/config/modules/gameplay/ConfigurableInventoryOverflowEvent.java
Labels: type: fix

#315 Do A Barrel Roll Protocol
  leaf-server/minecraft-patches/features/0165-Protocol-Core.patch
  leaf-server/src/main/java/org/dreeam/leaf/config/modules/network/ProtocolSupport.java
  leaf-server/src/main/java/org/dreeam/leaf/protocol/DoABarrelRollPackets.java
  leaf-server/src/main/java/org/dreeam/leaf/protocol/DoABarrelRollProtocol.java
  leaf-server/src/main/java/org/dreeam/leaf/protocol/LeafCustomPayload.java
  leaf-server/src/main/java/org/dreeam/leaf/protocol/Protocol.java
  leaf-server/src/main/java/org/dreeam/leaf/protocol/Protocols.java
Labels: type: feature

#307 update async chunk send
  leaf-server/minecraft-patches/features/0132-Async-chunk-send.patch
  leaf-server/minecraft-patches/features/0132-Async-chunk-sending.patch
  leaf-server/paper-patches/features/0036-async-chunk-send.patch
  leaf-server/src/main/java/org/dreeam/leaf/async/AsyncChunkSending.java
  leaf-server/src/main/java/org/dreeam/leaf/async/chunk/AsyncChunkSend.java
  leaf-server/src/main/java/org/dreeam/leaf/async/chunk/AsyncChunkSendThread.java
  leaf-server/src/main/java/org/dreeam/leaf/config/modules/async/AsyncChunkSend.java
Labels: type: fix

#316 move and flush position while knockback
  leaf-server/minecraft-patches/features/0171-move-and-flush-location-while-knockback.patch
  leaf-server/src/main/java/org/dreeam/leaf/config/modules/gameplay/Knockback.java
Labels: type: feature

#322 Prevent overriding spark flags
  leaf-server/src/main/java/org/dreeam/leaf/config/LeafConfig.java
Labels: type: fix

#326 Add configurable death item drop knockback
  leaf-server/minecraft-patches/features/0177-Add-configurable-death-item-drop-knockback-settings.patch
  leaf-server/src/main/java/org/dreeam/leaf/config/modules/gameplay/DeathItemDropKnockback.java
Labels: type: feature

#323 optimize tracker
  leaf-server/minecraft-patches/features/0085-Multithreaded-Tracker.patch
  leaf-server/minecraft-patches/features/0143-Optimize-addOrUpdateTransientModifier.patch
  leaf-server/minecraft-patches/features/0164-Protocol-Core.patch
  leaf-server/minecraft-patches/features/0178-optimize-AttributeMap.patch
  leaf-server/minecraft-patches/features/0179-optimize-getScaledTrackingDistance.patch
  leaf-server/minecraft-patches/features/0180-optimize-SynchedEntityData-packDirty.patch
  leaf-server/paper-patches/features/0024-Multithreaded-Tracker.patch
  leaf-server/src/main/java/org/dreeam/leaf/async/tracker/MultithreadedTracker.java
  leaf-server/src/main/java/org/dreeam/leaf/protocol/DoABarrelRollProtocol.java
  leaf-server/src/main/java/org/dreeam/leaf/util/map/AttributeInstanceArrayMap.java
Labels: type: optimization

#328 Integrate Build API into CI workflow
  .github/workflows/publish-api.yml
Labels: type: misc

#327 Optimize isEyeInFluid
  leaf-server/minecraft-patches/features/0179-Optimize-isEyeInFluid.patch
  leaf-server/minecraft-patches/features/0180-Paw-optimization.patch
  leaf-server/src/main/java/org/dreeam/leaf/config/modules/opt/EyeFluidCache.java
Labels: type: optimization
