Repository Winds-Studio/Leaf, pull requests merged in 2025-07, with the labels that each got.

#393 fix TRACKED entities not count
  leaf-archived-patches/removed/1.21.7/0008-Pufferfish-Optimize-mob-spawning.patch
  leaf-server/minecraft-patches/features/0261-optimize-mob-spawning.patch
  leaf-server/minecraft-patches/features/0263-throttle-mob-spawning.patch
  leaf-server/minecraft-patches/features/0268-optimize-random-tick.patch
  leaf-server/paper-patches/features/0008-Purpur-Server-Paper-Changes.patch
  leaf-server/paper-patches/features/0009-Fix-Pufferfish-and-Purpur-patches.patch
  leaf-server/paper-patches/features/0010-Simpler-ShapelessRecipe-comparison-for-vanilla.patch
  leaf-server/paper-patches/features/0011-Print-stack-trace-for-plugins-not-shutting-down-task.patch
  leaf-server/paper-patches/features/0012-SIMD-support.patch
  leaf-server/paper-patches/features/0013-Make-book-writing-configurable.patch
  leaf-server/paper-patches/features/0014-Do-not-log-legacy-Material-initialization.patch
  leaf-server/paper-patches/features/0015-Do-not-log-Not-Secure-marker.patch
  leaf-server/paper-patches/features/0016-Reduce-array-allocations.patch
  leaf-server/paper-patches/features/0017-CraftBukkit-UUID-to-world-map.patch
  leaf-server/paper-patches/features/0018-Specific-interval-TPS-API.patch
  leaf-server/paper-patches/features/0019-5-second-TPS-average.patch
  leaf-server/paper-patches/features/0020-Last-tick-time-API.patch
  leaf-server/paper-patches/features/0021-Show-last-tick-time-in-tps-command.patch
  leaf-server/paper-patches/features/0022-Pre-compute-VarLong-sizes.patch
  leaf-server/paper-patches/features/0023-Optimize-VarInt-write-and-VarLong-write.patch
  leaf-server/paper-patches/features/0024-Virtual-thread-support.patch
  leaf-server/paper-patches/features/0025-Remove-Timings.patch
  leaf-server/paper-patches/features/0026-KeYi-Player-Skull-API.patch
  leaf-server/paper-patches/features/0027-Slice-Smooth-Teleports.patch
  leaf-server/paper-patches/features/0028-Leaves-Protocol-Core.patch
  leaf-server/paper-patches/features/0029-Leaves-Replay-Mod-API.patch
  leaf-server/paper-patches/features/0030-Skip-event-if-no-listeners.patch
  leaf-server/paper-patches/features/0031-SparklyPaper-Optimize-canSee-checks.patch
  leaf-server/paper-patches/features/0032-Including-5s-in-getTPS.patch
  leaf-server/paper-patches/features/0033-Don-t-throw-exception-on-missing-ResourceKey-value.patch
  leaf-server/paper-patches/features/0034-Virtual-Thread-for-async-scheduler.patch
  leaf-server/paper-patches/features/0035-Mirai-Configurable-chat-message-signatures.patch
  leaf-server/paper-patches/features/0036-Matter-Secure-Seed.patch
  leaf-server/paper-patches/features/0037-Faster-random-generator.patch
  leaf-server/paper-patches/features/0038-Configurable-unknown-command-message.patch
  leaf-server/paper-patches/features/0039-Replace-world-map-with-optimized-collection.patch
  leaf-server/paper-patches/features/0040-Cache-CraftEntityType-minecraftToBukkit-convert.patch
  leaf-server/paper-patches/features/0041-Multithreaded-Tracker.patch
  leaf-server/paper-patches/features/0042-Asynchronous-locator.patch
  leaf-server/paper-patches/features/0043-EMC-Don-t-use-snapshots-for-acquiring-blockstate.patch
  leaf-server/paper-patches/features/0044-Faster-CraftServer-getworlds-list-creation.patch
  leaf-server/paper-patches/features/0045-Cache-chunk-key.patch
  leaf-server/paper-patches/features/0046-Async-structure-locate-api.patch
  leaf-server/paper-patches/features/0047-PlayerInventoryOverflowEvent.patch
  leaf-server/paper-patches/features/0048-SparklyPaper-Parallel-world-ticking.patch
  leaf-server/paper-patches/features/0049-Paper-PR-Throttle-failed-spawn-attempts.patch
  leaf-server/paper-patches/features/0050-Async-playerdata-saving.patch
  leaf-server/paper-patches/features/0051-Async-chunk-sending.patch
  leaf-server/paper-patches/features/0052-Optimise-player-movement-checks.patch
  leaf-server/paper-patches/features/0053-optimise-ReferenceList.patch
  leaf-server/paper-patches/features/0054-cache-getBiome.patch
  leaf-server/paper-patches/features/0055-dump-pwt-thread.patch
  leaf-server/paper-patches/features/0056-Paw-optimization.patch
  leaf-server/paper-patches/features/0057-optimize-despawn.patch
  leaf-server/paper-patches/features/0058-optimize-mob-spawning.patch
  leaf-server/src/main/java/gg/pufferfish/pufferfish/util/AsyncExecutor.java
Labels: type: fix

#390 Refactor async entity tracker
  leaf-server/minecraft-patches/features/0169-Multithreaded-Tracker.patch
  leaf-server/minecraft-patches/features/0186-Cache-chunk-key.patch
  leaf-server/minecraft-patches/features/0194-Optimize-checking-nearby-players-for-spawning.patch
  leaf-server/minecraft-patches/features/0201-optimize-mob-despawn.patch
  leaf-server/minecraft-patches/features/0209-Async-chunk-sending.patch
  leaf-server/minecraft-patches/features/0211-SparklyPaper-Parallel-world-ticking.patch
  leaf-server/minecraft-patches/features/0212-SparklyPaper-Track-each-world-MSPT.patch
  leaf-server/minecraft-patches/features/0216-Use-BFS-on-getSlopeDistance.patch
  leaf-server/minecraft-patches/features/0222-Micro-optimizations-for-random-tick.patch
  leaf-server/minecraft-patches/features/0230-Async-target-finding.patch
  leaf-server/minecraft-patches/features/0237-Protocol-Core.patch
  leaf-server/minecraft-patches/features/0257-optimize-mob-spawning.patch
  leaf-server/minecraft-patches/features/0264-optimize-random-tick.patch
  leaf-server/minecraft-patches/features/0271-Paw-optimization.patch
  leaf-server/paper-patches/features/0042-Multithreaded-Tracker.patch
  leaf-server/paper-patches/features/0043-Asynchronous-locator.patch
  leaf-server/src/main/java/org/dreeam/leaf/async/FixedThreadExecutor.java
  leaf-server/src/main/java/org/dreeam/leaf/async/ShutdownExecutors.java
  leaf-server/src/main/java/org/dreeam/leaf/async/tracker/AsyncTracker.java
  leaf-server/src/main/java/org/dreeam/leaf/async/tracker/MultithreadedTracker.java
  leaf-server/src/main/java/org/dreeam/leaf/async/tracker/TrackerCtx.java
  leaf-server/src/main/java/org/dreeam/leaf/async/tracker/TrackerTask.java
  leaf-server/src/main/java/org/dreeam/leaf/config/modules/async/MultithreadedTracker.java
  leaf-server/src/main/java/org/dreeam/leaf/util/EntitySlice.java
  leaf-server/src/main/java/org/dreeam/leaf/util/queue/MpmcQueue.java
Labels: type: fix, type: optimization

#399 optimize despawn
  leaf-server/minecraft-patches/features/0201-optimize-mob-despawn.patch
  leaf-server/minecraft-patches/features/0211-SparklyPaper-Parallel-world-ticking.patch
  leaf-server/minecraft-patches/features/0216-Use-BFS-on-getSlopeDistance.patch
  leaf-server/minecraft-patches/features/0222-Micro-optimizations-for-random-tick.patch
  leaf-server/minecraft-patches/features/0230-Async-target-finding.patch
  leaf-server/minecraft-patches/features/0257-optimize-mob-spawning.patch
  leaf-server/minecraft-patches/features/0264-optimize-random-tick.patch
  leaf-server/minecraft-patches/features/0271-Paw-optimization.patch
  leaf-server/paper-patches/features/0059-optimize-despawn.patch
  leaf-server/src/main/java/org/dreeam/leaf/config/modules/opt/OptimizeDespawn.java
  leaf-server/src/main/java/org/dreeam/leaf/world/DespawnMap.java
  leaf-server/src/main/java/org/dreeam/leaf/world/DespawnVectorAPI.java
Labels: type: optimization

#409 optimize entity despawn
  leaf-server/minecraft-patches/features/0201-optimize-mob-despawn.patch
  leaf-server/minecraft-patches/features/0211-SparklyPaper-Parallel-world-ticking.patch
  leaf-server/minecraft-patches/features/0216-Use-BFS-on-getSlopeDistance.patch
  leaf-server/minecraft-patches/features/0222-Micro-optimizations-for-random-tick.patch
  leaf-server/minecraft-patches/features/0230-Async-target-finding.patch
  leaf-server/minecraft-patches/features/0257-optimize-mob-spawning.patch
  leaf-server/minecraft-patches/features/0264-optimize-random-tick.patch
  leaf-server/minecraft-patches/features/0271-Paw-optimization.patch
  leaf-server/paper-patches/features/0059-optimize-despawn.patch
  leaf-server/src/main/java/org/dreeam/leaf/config/modules/opt/OptimizeDespawn.java
  leaf-server/src/main/java/org/dreeam/leaf/world/DespawnMap.java
  leaf-server/src/main/java/org/dreeam/leaf/world/DespawnVectorAPI.java
Labels: type: optimization

#421 [ci skip] updated readme
  README.md
  public/readme/README_CN.md
Labels: type: misc

#419 fix async tracker bundle packet too large
  leaf-server/minecraft-patches/features/0169-Multithreaded-Tracker.patch
  leaf-server/src/main/java/org/dreeam/leaf/async/tracker/AsyncTracker.java
  leaf-server/src/main/java/org/dreeam/leaf/async/tracker/TrackerCtx.java
Labels: type: fix

#423 Simplified AsyncPath
  leaf-server/src/main/java/org/dreeam/leaf/async/path/AsyncPath.java
  leaf-server/src/main/java/org/dreeam/leaf/async/path/AsyncPathProcessor.java
  leaf-server/src/main/java/org/dreeam/leaf/async/path/PathProcessState.java
Labels: type: optimization

#432 fix async tracker cause player velocity not updated
  leaf-server/src/main/java/org/dreeam/leaf/async/tracker/TrackerCtx.java
Labels: type: fix

#427 optimize MpmcQueue memory layout
  leaf-server/src/main/java/org/dreeam/leaf/util/queue/MpmcQueue.java
Labels: type: optimization

#425 Custom NonNullList
  leaf-server/minecraft-patches/features/0277-Custom-NonNullList.patch
  leaf-server/minecraft-patches/features/0278-Optimise-TextColor.patch
  leaf-server/src/main/java/org/dreeam/leaf/util/list/OptimizedNonNullListArrayList.java
Labels: type: optimization
