Repository Winds-Studio/Leaf, pull requests merged in 2025-04, with the labels that each got.

#274 Allow Non-ASCII character in unquoted string of command argument
  leaf-server/minecraft-patches/features/0158-Allow-non-ascii-character-in-unquoted-string-of-comm.patch
Labels: type: feature

#278 Fix race condition in IteratorSafeOrderedReferenceSet
  leaf-server/paper-patches/features/0004-Pufferfish-Optimize-mob-spawning.patch
Labels: type: fix

#291 update Async target finding
  leaf-server/minecraft-patches/features/0156-Async-Target-Finding.patch
  leaf-server/minecraft-patches/features/0156-Async-target-finding.patch
Labels: type: fix, type: optimization

#287 Couple fixes and improvements
  leaf-server/minecraft-patches/features/0127-Improve-sorting-in-SortedArraySet.patch
  leaf-server/minecraft-patches/features/0127-Optimize-AABB.patch
  leaf-server/minecraft-patches/features/0128-Make-removeIf-slightly-faster.patch
  leaf-server/minecraft-patches/features/0129-Optimize-LinearPalette.patch
  leaf-server/minecraft-patches/features/0130-Slightly-optimized-VarInt-write.patch
  leaf-server/minecraft-patches/features/0131-Rewrite-ClientboundLightUpdatePacketData.patch
  leaf-server/minecraft-patches/features/0132-Async-chunk-sending.patch
  leaf-server/minecraft-patches/features/0133-Some-Optimizations-on-SerializableChunkData.patch
  leaf-server/minecraft-patches/features/0133-Spawner-Configurations.patch
  leaf-server/minecraft-patches/features/0134-Rework-ChunkHolderManager.patch
  leaf-server/minecraft-patches/features/0134-SparklyPaper-Parallel-world-ticking.patch
  leaf-server/minecraft-patches/features/0135-SparklyPaper-Track-each-world-MSPT.patch
  leaf-server/minecraft-patches/features/0136-PaperPR-Fix-cancelled-Projectile-Events-still-consum.patch
  leaf-server/minecraft-patches/features/0137-Optimize-SetLookAndInteract-and-NearestVisibleLiving.patch
  leaf-server/minecraft-patches/features/0138-Remove-streams-on-InsideBrownianWalk.patch
  leaf-server/minecraft-patches/features/0139-Use-BFS-on-getSlopeDistance.patch
  leaf-server/minecraft-patches/features/0140-Paper-PR-Throttle-failed-spawn-attempts.patch
  leaf-server/minecraft-patches/features/0141-Improve-BlockEntity-ticking-isRemoved-check.patch
  leaf-server/minecraft-patches/features/0142-Raytrace-AntiXray-SDK-integration.patch
  leaf-server/minecraft-patches/features/0143-Optimize-addOrUpdateTransientModifier.patch
  leaf-server/minecraft-patches/features/0144-Optimize-ContextMap.create.patch
  leaf-server/minecraft-patches/features/0145-Micro-optimizations-for-random-tick.patch
  leaf-server/minecraft-patches/features/0146-Remove-streams-on-updateConnectedPlayersWithinRange.patch
  leaf-server/minecraft-patches/features/0147-Remove-streams-on-PlayerDetector.patch
  leaf-server/minecraft-patches/features/0148-Async-Block-Finding.patch
  leaf-server/minecraft-patches/features/0149-Use-direct-iteration-on-Sensing.tick.patch
  leaf-server/minecraft-patches/features/0150-Optimise-non-flush-packet-sending.patch
  leaf-server/minecraft-patches/features/0151-Prevent-double-chunk-retrieving-in-entity-fluid-push.patch
  leaf-server/minecraft-patches/features/0152-Null-handling-on-MultifaceSpreader.patch
  leaf-server/minecraft-patches/features/0153-More-virtual-threads.patch
  leaf-server/minecraft-patches/features/0154-Replace-ConcurrentLong2ReferenceChainedHashTable-wit.patch
  leaf-server/minecraft-patches/features/0155-Async-target-finding.patch
  leaf-server/minecraft-patches/features/0156-Reworked-ChunkHolderManager.patch
  leaf-server/minecraft-patches/features/0157-Optimize-ThreadedTicketLevelPropagator.patch
  leaf-server/minecraft-patches/features/0158-Optimise-MobEffectUtil-getDigSpeedAmplification.patch
  leaf-server/minecraft-patches/features/0159-Optimise-chunkUnloads.patch
  leaf-server/src/main/java/org/dreeam/leaf/util/map/spottedleaf/LeafConcurrentLong2ReferenceChainedHashTable.java
Labels: type: fix, type: optimization

#293 Fixed NANOSECONDS pos
  leaf-server/src/main/java/org/stupidcraft/linearpaper/region/LinearRegionFile.java
Labels: type: fix

#294 improve Async target finding
  leaf-server/minecraft-patches/features/0155-Async-target-finding.patch
  leaf-server/src/main/java/org/dreeam/leaf/async/ai/AsyncGoal.java
  leaf-server/src/main/java/org/dreeam/leaf/async/ai/AsyncGoalExecutor.java
Labels: type: fix

#290 optimize BlockEntityType#isValid
  leaf-server/minecraft-patches/features/0159-optimize-BlockEntityType-isValid.patch
Labels: type: optimization

#299 optimize AttributeMap
  leaf-server/minecraft-patches/features/0085-Multithreaded-Tracker.patch
  leaf-server/src/main/java/org/dreeam/leaf/config/modules/async/MultithreadedTracker.java
Labels: type: optimization
