Repository Winds-Studio/Leaf, pull requests merged in 2025-09, with the labels that each got.

#481 optimize entity tick effects
  leaf-server/minecraft-patches/features/0297-optimize-tickEffects.patch
Labels: type: optimization

#491 Pluto: expose Direction$Plane's faces
  leaf-server/minecraft-patches/features/0245-optimize-mob-spawning.patch
  leaf-server/minecraft-patches/features/0252-optimize-random-tick.patch
  leaf-server/minecraft-patches/features/0258-Paw-optimization.patch
  leaf-server/minecraft-patches/features/0297-Pluto-Expose-Direction-Plane-s-faces.patch
  leaf-server/minecraft-patches/features/0298-Pluto-reduce-allocation.patch
Labels: type: optimization

#493 Parallel World Ticking API for monitoring tools
  leaf-api/paper-patches/features/0020-Fish-Parallel-World-Ticking-API.patch
  leaf-server/paper-patches/features/0048-Fish-Parallel-World-Ticking-API.patch
  leaf-server/paper-patches/features/0049-Paper-PR-Throttle-failed-spawn-attempts.patch
  leaf-server/paper-patches/features/0050-Async-playerdata-saving.patch
  leaf-server/paper-patches/features/0051-Async-chunk-sending.patch
  leaf-server/paper-patches/features/0052-Optimise-player-movement-checks.patch
  leaf-server/paper-patches/features/0053-optimise-ReferenceList.patch
  leaf-server/paper-patches/features/0054-cache-getBiome.patch
  leaf-server/paper-patches/features/0055-dump-pwt-thread.patch
  leaf-server/paper-patches/features/0056-Paw-optimization.patch
  leaf-server/paper-patches/features/0057-optimize-despawn.patch
  leaf-server/paper-patches/features/0058-optimize-mob-spawning.patch
  leaf-server/paper-patches/features/0059-Toggleable-async-catcher.patch
  leaf-server/paper-patches/features/0060-cache-profile-data.patch
  leaf-server/paper-patches/features/0061-Bump-netty-to-4.2.x.patch
Labels: type: feature

#499 fix(replay): run ServerPhotographer player ops on main thread
  leaf-server/src/main/java/org/leavesmc/leaves/replay/ServerPhotographer.java
Labels: type: fix

#454 Update optimize entity despawn
  leaf-server/minecraft-patches/features/0193-optimize-mob-despawn.patch
  leaf-server/minecraft-patches/features/0299-Only-update-frozen-ticks-if-changed.patch
  leaf-server/paper-patches/features/0057-optimize-despawn.patch
  leaf-server/src/main/java/org/dreeam/leaf/config/modules/opt/OptimizeDespawn.java
  leaf-server/src/main/java/org/dreeam/leaf/util/KDTree2D.java
  leaf-server/src/main/java/org/dreeam/leaf/util/KDTree3D.java
  leaf-server/src/main/java/org/dreeam/leaf/util/PartialSort.java
  leaf-server/src/main/java/org/dreeam/leaf/world/DespawnMap.java
  leaf-server/src/main/java/org/dreeam/leaf/world/DespawnVectorAPI.java
Labels: type: optimization, type: general
