Repository Winds-Studio/Leaf, pull requests merged in 2025-06, with the labels that each got.

#333 Async Data Read for Parallel World Ticking
  leaf-server/minecraft-patches/features/0134-SparklyPaper-Parallel-world-ticking.patch
  leaf-server/minecraft-patches/features/0135-SparklyPaper-Track-each-world-MSPT.patch
  leaf-server/minecraft-patches/features/0139-Use-BFS-on-getSlopeDistance.patch
  leaf-server/minecraft-patches/features/0145-Micro-optimizations-for-random-tick.patch
  leaf-server/minecraft-patches/features/0153-Async-target-finding.patch
  leaf-server/minecraft-patches/features/0163-Protocol-Core.patch
  leaf-server/minecraft-patches/features/0179-Paw-optimization.patch
  leaf-server/paper-patches/features/0030-SparklyPaper-Parallel-world-ticking.patch
  leaf-server/src/main/java/org/dreeam/leaf/async/world/ReadOperationType.java
  leaf-server/src/main/java/org/dreeam/leaf/async/world/WorldReadRequest.java
  leaf-server/src/main/java/org/dreeam/leaf/config/modules/async/SparklyPaperParallelWorldTicking.java
Labels: type: fix, scope: parallel-world-ticking

#349 Add BlockExplosionHitEvent
  leaf-api/src/main/java/org/dreeam/leaf/event/BlockExplosionHitEvent.java
  leaf-server/minecraft-patches/features/0189-Add-BlockExplosionHitEvent.patch
Labels: type: feature

#351 Fix grammatical issues in README.md
  README.md
Labels: type: misc

#346 Add old Blast Protection explosion knockback behavior
  leaf-server/minecraft-patches/features/0161-Sakura-Optimise-check-inside-blocks-and-traverse-blo.patch
  leaf-server/minecraft-patches/features/0162-Sakura-copy-EntityList-implementation-to-BasicEntity.patch
  leaf-server/minecraft-patches/features/0190-Old-Blast-Protection-explosion-knockback.patch
  leaf-server/src/main/java/org/dreeam/leaf/config/modules/gameplay/Knockback.java
  leaf-server/src/main/java/org/dreeam/leaf/util/map/BlockPosIterator.java
Labels: type: feature

#357 optimize random tick
  leaf-server/minecraft-patches/features/0192-optimize-random-tick.patch
  leaf-server/src/main/java/org/dreeam/leaf/config/modules/opt/OptimizeRandomTick.java
  leaf-server/src/main/java/org/dreeam/leaf/world/RandomTickSystem.java
Labels: type: optimization

#359 Optimize random tick
  leaf-server/minecraft-patches/features/0192-optimize-random-tick.patch
  leaf-server/src/main/java/org/dreeam/leaf/config/modules/opt/OptimizeRandomTick.java
  leaf-server/src/main/java/org/dreeam/leaf/world/RandomTickSystem.java
Labels: type: optimization

#382 optimize collectSpawningChunks
  leaf-server/minecraft-patches/features/0262-optimize-mob-spawning.patch
  leaf-server/minecraft-patches/features/0269-optimize-random-tick.patch
  leaf-server/minecraft-patches/features/0272-Paw-optimization.patch
  leaf-server/src/main/java/org/dreeam/leaf/world/NatureSpawnChunkMap.java
Labels: type: optimization
